# Generated by Django 2.2.6 on 2019-10-31 07:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='labels',
            field=models.CharField(default='Add label', max_length=50),
        ),
        migrations.CreateModel(
            name='BoardInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=50)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trelloapp.Board')),
            ],
        ),
    ]
